name: Integration Tests

on: 
  push:
    branches:
      - main
    paths:
      - child_repo

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout/@v3
        with:
          submodules: true

      - name: Integration test
        uses: cypress-io/github-action@v5
        with:
          build: npm run build:dev
          start: npm run start:wait-on
